export const GET_WEATHER = "GET_WEATHER";
export const SEARCH_INPUT = "SEARCH_INPUT";
export const SET_BACKGROUND = "SET_BACKGROUND";
export const FORECAST_WEATHER = "FORECAST_WEATHER";
export const SET_LOADING = "SET_LOADING";
export const NOT_FOUND = "NOT_FOUND";
